### ISSUE TITLE
CallerID problem during call transfer.

### ISSUE THREAD

**Issue by rranjan-rly** [ptiriset/Asterisk#1]
The test setup has CoreIP T27G phones. Let us say there are three users A, B and C. The scenario is explained below.

1. A dials B -> The caller-id displayed at phone B shows A.
2. B transfers this call to C. The caller-id displayed at C shows B and not A in both the cases of attended as well as blind transfer. 
3. The result desired is that caller-id of A must be shown to C.

**Comment by raj4944** [comment]
Sir, I will try this on Grandtream GPX1625 phones and share the observations.

**Comment by raj4944** [comment]
Sir, Observations by using Asterisk server & Grandstream GPX1625 IP Phone.
attended Transfer:
1. A-> dials B -->caller id at phone B shows A. B->> answers the call
2. B-> press hold.    A--> gets MOH,  B-> dials C the caller id is shows B
3. C-> answers the call.   B>> can now toggle between A & C by putting either of them on hold. since B has already informed to C about the call from A , so sending caller id  of A to be shown on C seems irrelevant.
4. B -> presses Transfer key A & C both are on MOH.
5. B-> evoke Hold key and call gets transferred to C. 
6. A & C are in Talk mode.  B becomes idle.
Blind Transfer
1. A dials B     -> Caller id displayed at B  shows A
2. B -> answers the call & press Transfer key ( in attended transfer its hold key).  A gets MOH.
3. B -> dials C. caller id displayed at C  shows A . ringing start at C & A gets RBT (MOH is stopped) and B becomes idle. all the three actions >C start ringing, RBT to A (MOH is off) & DEVICE_STATE B is idle.
4. C answers the call. A&C are talk mode with caller id at C shows A.
Call Forward: 
1. A dials B  --> caller id displayed at B shows of A. B rings.
2. B -> without answering the call,  choose to forward the call to C thus presses 'Forward' key  ( 'Forward' option is displayed on display of phone B. B presses the corresponding key to forward the call)
3. A -> gets continuous RBT. ringing continues at B
4. B --> in Ringing condition presses Forward key  (dial option for B is evoked) and Dials C
5. C -> gets ring with caller id displayed at C shows A. 
6. A -> continues with RBT, C is ringing &  DEVICE_STATE of B is idle.
7. C -> answers the call.
8. => A & C are in call.

**Comment by rranjan-rly** [comment]
Hi,

Did you do this test on a bare Asterisk configuration or the configuration
generated by the code?

राकेश रंजन
कार्यकारी निदेशक
रेल मंत्रालय, भारत सरकार

**Comment by rranjan-rly** [comment]
The Yealink  phone was not honoring the P-Assert-Identity (PAI) in its default configuration. The phone configuration was changed to add the line account.1.cid_source = 2. This enables the PAI and the phone is now showing the correct CLI when we transfer a call.

**Comment by rranjan-rly** [comment]
Closed.

**Comment by raj4944** [comment]
sir, i tried it on bare Asterisk configuration. i will check with tool, if i get the same results.
